# Generated by Django 5.1.7 on 2025-04-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=20, null=True)),
                ('leader_id', models.CharField(blank=True, max_length=6, null=True)),
                ('mate1_id', models.CharField(blank=True, max_length=6, null=True)),
                ('mate2_id', models.CharField(blank=True, max_length=6, null=True)),
                ('mate3_id', models.CharField(blank=True, max_length=6, null=True)),
                ('mate4_id', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
