# Generated by Django 5.1.7 on 2025-04-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
