# Generated by Django 5.1.7 on 2025-04-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('dept_id', models.CharField(blank=True, max_length=3, null=True)),
                ('instructor_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
    ]
