# Generated by Django 5.1.7 on 2025-04-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=15)),
                ('round', models.CharField(max_length=2)),
                ('attendance', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'attendance',
                'constraints': [models.UniqueConstraint(fields=('team_id', 'round'), name='unique_attendance')],
            },
        ),
    ]
